name = "execline"
version = "2.8.2.0"
description = "ska scripting libraries for stuff"
authors = ["skalibs <?@skarnet.org>"]
license = "ISC"
tracked_files = [""]
dependencies = []
provides = []
conflicts = []
reccomendations = []
arch = "x86_64"
