name = "bash"
version = "5.1.8"
description = "gnu bash shell"
authors = ["GNU <your@mom.sucks>"]
license = "gpl"
tracked_files = [""]
dependencies = []
provides = ["bash"]
conflicts = []
reccomendations = []
arch = "x86_64"
