name = "ncurses"
version = "6.2"
description = "terminal control go brr"
authors = ["lol <dont@know.author>"]
license = ""
tracked_files = [""]
dependencies = []
provides = ["bash"]
conflicts = []
reccomendations = []
arch = "x86_64"
