name = "static-get"
version = "1.0.0"
description = "static-get package manager"
authors = ["??? <un@known.author>"]
license = ""
tracked_files = [""]
dependencies = ["bash"]
provides = [""]
conflicts = []
reccomendations = []
arch = "x86_64"
