name = "rustysd"
version = "1.0.0"
description = "rustysd is a rust clone of systemd's service manager"
authors = ["lol <dont@know.author>"]
license = ""
tracked_files = [""]
dependencies = []
provides = [""]
conflicts = []
reccomendations = []
arch = "x86_64"
