name = "skalibs"
version = "2.11.1.0"
description = "ska libraries for stuff"
authors = ["skalibs <?@skarnet.org>"]
license = "ISC"
tracked_files = [""]
dependencies = []
provides = []
conflicts = []
reccomendations = []
arch = "x86_64"
