name = "notools"
version = "1.0.0"
description = "jnat notools go brr"
authors = ["Michal <michal@tar.black>"]
license = "nolicense"
tracked_files = [""]
dependencies = []
provides = []
conflicts = []
reccomendations = []
arch = "any"
